# Initial Data Cleaning - ONS Postcode Directory Dataset
### Notebook Done By: Kai/Su

This notebook contains some of the processes for the Initial Data Cleaning phase, specifically for cleaning the ONS Postcode Directory dataset. This notebook covers the process of cleaning the ONS Postcode Directory dataset.

In [ ]:
# Importing libraries

import pandas as pd

In [ ]:
# Loading the ONS Postcode Directory dataset

df = pd.read_csv("../../data/raw/ONSPD_AUG_2025_UK.csv", low_memory=False)
df.head()

,pcd7,pcd8,pcds,dointr,doterm,cty25cd,ced25cd,lad25cd,wd25cd,parncp25cd,...,lep21cd1,lep21cd2,pfa23cd,imd20ind,cal24cd,icb23cd,oa21cd,lsoa21cd,msoa21cd,ruc21ind
0,AB1 0AA,AB1 0AA,AB1 0AA,198001,199606.0,S99999999,S99999999,S12000033,S13002843,S99999999,...,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516,1
1,AB1 0AB,AB1 0AB,AB1 0AB,198001,199606.0,S99999999,S99999999,S12000033,S13002843,S99999999,...,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516,1
2,AB1 0AD,AB1 0AD,AB1 0AD,198001,199606.0,S99999999,S99999999,S12000033,S13002843,S99999999,...,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516,1
3,AB1 0AE,AB1 0AE,AB1 0AE,199402,199606.0,S99999999,S99999999,S12000034,S13002864,S99999999,...,S99999999,NaN,S23000009,5069,S99999999,S99999999,S00138891,S01013856,S02002577,5
4,AB1 0AF,AB1 0AF,AB1 0AF,199012,199207.0,S99999999,S99999999,S12000033,S13002843,S99999999,...,S99999999,NaN,S23000009,6253,S99999999,S99999999,S00137241,S01013487,S02002515,1

In [ ]:
# Reviewing columns in the ONS Postcode Directory dataset

df.columns

Index(['pcd7', 'pcd8', 'pcds', 'dointr', 'doterm', 'cty25cd', 'ced25cd',
       'lad25cd', 'wd25cd', 'parncp25cd', 'usrtypind', 'east1m', 'north1m',
       'gridind', 'hlth19cd', 'nhser24cd', 'ctry25cd', 'rgn25cd', 'ssr95cd',
       'pcon24cd', 'eer20cd', 'educ23cd', 'ttwa15cd', 'pco19cd', 'itl25cd',
       'wdstl05cd', 'oa01cd', 'wdcas03cd', 'npark16cd', 'lsoa01cd', 'msoa01cd',
       'ruc01ind', 'oac01ind', 'oa11cd', 'lsoa11cd', 'msoa11cd', 'wz11cd',
       'sicbl24cd', 'bua24cd', 'ruc11ind', 'oac11ind', 'lat', 'long',
       'lep21cd1', 'lep21cd2', 'pfa23cd', 'imd20ind', 'cal24cd', 'icb23cd',
       'oa21cd', 'lsoa21cd', 'msoa21cd', 'ruc21ind'],
      dtype='object')

In [ ]:
# Keeping only relevant columns in the ONS Postcode Directory dataset

df = pd.read_csv(
    "../../data/raw/ONSPD_AUG_2025_UK.csv",
    usecols=["pcds", "lat", "long"],
    low_memory=False
)

df.head()

      pcds        lat      long
0  AB1 0AA  57.101459 -2.242858
1  AB1 0AB  57.102539 -2.246315
2  AB1 0AD  57.100541 -2.248349
3  AB1 0AE  57.084429 -2.255714
4  AB1 0AF  57.096641 -2.258109

In [ ]:
# Standardising column names in the ONS Postcode Directory dataset into more-readable formats

df = df.rename(columns={"pcds": "postcode", "lat": "latitude", "long": "longitude"})
df.head()

  postcode   latitude  longitude
0  AB1 0AA  57.101459  -2.242858
1  AB1 0AB  57.102539  -2.246315
2  AB1 0AD  57.100541  -2.248349
3  AB1 0AE  57.084429  -2.255714
4  AB1 0AF  57.096641  -2.258109

In [ ]:
# Standardising postcodes in the ONS Postcode Directory dataset

df["postcode"] = df["postcode"].astype(str).str.upper().str.replace(" ", "", regex=False)
df.head()

  postcode   latitude  longitude
0   AB10AA  57.101459  -2.242858
1   AB10AB  57.102539  -2.246315
2   AB10AD  57.100541  -2.248349
3   AB10AE  57.084429  -2.255714
4   AB10AF  57.096641  -2.258109

In [ ]:
# Ensuring that the coordinates are of numeric data types

df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")

In [ ]:
# Dropping rows with missing values and ensuring that only postcodes within the UK are included in the ONS Postcode Directory dataset

df = df.dropna(subset=["postcode", "latitude", "longitude"])
df = df[(df["latitude"].between(49, 61)) & (df["longitude"].between(-9, 3))]  # UK approx range

In [ ]:
# Dropping rows with duplicate postcodes in the ONS Postcode Directory dataset

df = df.drop_duplicates(subset=["postcode"])

In [ ]:
# Reviewing descriptive statistics of columns in the ONS Postcode Directory dataset

print("Rows:", len(df))
df.describe(include="all")

Rows: 2693630

       postcode      latitude     longitude
count   2693630  2.693630e+06  2.693630e+06
unique  2693630           NaN           NaN
top      AB10AA           NaN           NaN
freq          1           NaN           NaN
mean        NaN  5.269302e+01 -1.654052e+00
std         NaN  1.586221e+00  1.588993e+00
min         NaN  4.989197e+01 -8.163139e+00
25%         NaN  5.149302e+01 -2.616760e+00
50%         NaN  5.230384e+01 -1.519399e+00
75%         NaN  5.355800e+01 -3.265670e-01
max         NaN  6.080071e+01  1.762773e+00

In [ ]:
# Exporting the ONS Postcode Directory dataset into a CSV file

df.to_csv("../../data/partially_processed/onspd.csv", index=False)
print("Saved: onspd.csv")

Saved: ONSPD_AUG_2025_UK_cleaned.csv

The Initial Data Cleaning phase for the ONS Postcode Directory dataset has been completed, and the Initial Data Cleaning phase for the school dataset can begin.

The next notebook is ```notebooks/initial_data_cleaning/ofsted.ipynb```.